spring.application.name=accounting

# Temporary H2 Database Configuration (were using initially, commented out)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=user
#spring.datasource.password=user
#spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Added for Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/accounting
spring.datasource.username=haagahelia_admin
spring.datasource.password=haagahelia_admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


